---
# tasks file for test1

- name: Test ispisa varijable
  debug:
    msg: "{{ LOCATION }}"
  tags: test_ispisa_varijable

- name: Kreiranje HFS_HOME
  file: 
    path: "{{ HFS_HOME }}"
    state: directory
    owner: ansible

- name: Kreiranje HFS_HOME i prop1
  file: 
    #path: '"{{ HFS_HOME }}"prop1.conf'
    path: '/tmp/prop1.conf'
    state: touch    
    
- name: Kopiranje u HFS_HOME
  copy:
    content: "{{ LOCATION }}"
    dest: '/tmp/prop1.conf'

- name: Test ispisa varijable koja dictionary
  debug:
    msg: "{{item}}"
  with_dict: "{{ AAA }}"
  tags: print_dict
  
- name: Test ispisa varijable koja lista
  debug:
    msg: "{{item}}"
  loop: "{{ HFS.HOME_TREE }}"
  tags: print_list
  
- name: Test ispisa nested varijabli koje su liste
  debug:
    msg: "{{item[0]}}/{{item[1]}}"
  with_nested: 
    - "{{ HFS.HOME_TREE }}"
    - "{{ HFS.HOME_SUBF }}"
  tags: print_nested_lists
  

  
- name: Test kreiranja HFS nested
  file:
    path: "{{item[0]}}/{{item[1]}}"
    state: directory
    owner: "{{ HFS.USER }}"
    group: "{{ HFS.GROUP }}"
    mode: "u+rwx,g+rwx,o-rwx"
  with_nested: 
    - "{{ HFS.HOME_TREE }}"
    - "{{ HFS.SUBF }}"
  tags: create_hfs_tree
  

  